global:
  scrape_interval:     1m
  evaluation_interval: 1m

  external_labels:
      monitor: 'service-monitor'

scrape_configs:
  - job_name: 'service-monitor'

    scrape_interval: 1m
    
    static_configs:

      - targets: ['localhost:9100']
        labels:
          app: 'node-exporter'

      - targets: ['localhost:9712']
        labels:
          app: 'c-advisor'

      - targets: ['localhost:7000']
        labels:
          app: 'django'
